spring:
  application:
    name: invoice-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_invoice}
    username: ${MYSQL_USER:invoice}
    password: ${MYSQL_PASSWORD:invoice123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8084

jwt:
  secret: ${JWT_SECRET:8J+YjvCfpJPwn5ic8J+YmvCfmI3wn6Ww8J+ZgvCfpKM=}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
