services:
  mysql:
    image: mysql:8
    container_name: invoice-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_invoice
      MYSQL_USER: invoice
      MYSQL_PASSWORD: invoice123
    ports:
      - "3306:3306"
    volumes:
      - invoice_mysql_data:/var/lib/mysql

volumes:
  invoice_mysql_data:
