spring:
  application:
    name: auth-service

  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
   
  config:
    import: "optional:configserver:"   # qué importar
 
  cloud:
    config:
      uri: http://localhost:8888       # dónde está el config server

# Actuator exposure for local dev
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always